# Generated by Django 5.2.12 on 2026-06-02 00:15

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kurs nomi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Narxni 0 dan katta kiritishingiz kerak !!!')], verbose_name='Narx')),
                ('duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='0 dan katta raqam kiriting')], verbose_name='Davomiyligi')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(7, message='Yoshi 7 dan  oshganlar uchun !!!'), django.core.validators.MaxValueValidator(50, message='50 yoshgacha olinadi !!!')], verbose_name='Yosh')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Students_image/', verbose_name='Rasmi')),
                ('address', models.CharField(max_length=255, verbose_name='Manzil 📍')),
                ('mark', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message="Eng kichik ball 0 yoki undan katta bo'lishi kerak "), django.core.validators.MaxValueValidator(100, message="Eng yuqori ball 100 gavha bo'lishi kerak ")])),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(error_messages={'invalid': 'Iltimos raqamni namunadagidek kiriting !!!', 'null': 'Raqam kiritish shart !!! ', 'unique': 'Bu raqam orqali LOGIN mavjud !!!'}, help_text='Namuna: +998901234567', max_length=128, region='UZ', unique=True, verbose_name='TEL ☎️')),
                ('email', models.EmailField(error_messages={'invalid': 'Iltimos raqamni namunadagidek kiriting !!!', 'unique': 'Bu raqam orqali LOGIN qilingan !!!'}, help_text='Namuna misol@gmail.com', max_length=255, null=True, unique=True, verbose_name='Email 📧')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='api.course', verbose_name='Kursi')),
            ],
            options={
                'verbose_name': 'Talaba',
                'verbose_name_plural': 'Talabalar',
            },
        ),
    ]
