# Generated by Django 5.2.12 on 2026-06-04 16:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mark',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message="Eng kichik ball 0 yoki undan katta bo'lishi kerak "), django.core.validators.MaxValueValidator(100, message="Eng yuqori ball 100 gavha bo'lishi kerak ")], verbose_name='Baho'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Summa')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name="To'lov sanasi")),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.student', verbose_name='Talaba')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(20, message='Yoshi 20 dan  oshganlar uchun !!!'), django.core.validators.MaxValueValidator(60, message='60 yoshgacha olinadi !!!')], verbose_name='Yosh')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Teachers_image/', verbose_name='Rasmi')),
                ('skill', models.CharField(max_length=255, verbose_name='Tajriba')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='api.course', verbose_name='Kursi')),
            ],
            options={
                'verbose_name': "O'qituvchi",
                'verbose_name_plural': "O'qituvchilar",
            },
        ),
    ]
